<?php
/**
 * Created by PhpStorm.
 * User: sandeep
 * Date: 9/2/17
 * Time: 2:53 PM
 */

namespace Drupal\custom_migration\Plugin\migrate\process;


use Drupal\Component\Datetime\DateTimePlus;
use Drupal\migrate\MigrateExecutableInterface;
use Drupal\migrate\ProcessPluginBase;
use Drupal\migrate\Row;

/**
 * Provides process plugin.
 * Custom process plugin to migrate all foreign keys into comma imploded string in destination table.
 *
 *
 *
 * @MigrateProcessPlugin(
 *   id = "extended_iterator",
 *   handle_multiples = TRUE
 * )
 */
class ExtendedIterator extends ProcessPluginBase {
  
  protected  $idval = 0;
  public function iterateData($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property) {
    
    $source = $row->getSource();
//    print_r($row->getSource());
//    print_r($this->configuration);
    $data = \Drupal\Core\Database\Database::getConnection('default', $source['target'])
      ->select($source['table_name'], 'source_table_name')
      ->fields('source_table_name', [$this->configuration['source']])
      ->condition('source_table_name.' . $this->configuration['key'], $row->getSourceProperty($this->configuration['key']))
      ->execute()
      ->fetchCol();
    return implode(',', $data);
  }
  
  /**
   *
   * convert datetime to epoch timestamp
   *
   * @param $value
   * @param MigrateExecutableInterface $migrate_executable
   * @param Row $row
   * @param $destination_property
   * @return false|int
   */
  public function dateToTimestamp($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property){
    if($value){
      return strtotime($value);
    }
    return 0;
  }
  
  /**
   * @param $value
   * @param MigrateExecutableInterface $migrate_executable
   * @param Row $row
   * @param $destination_property
   * @return static
   */
  function timestampToDate($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property){
    if($value){
	return DateTimePlus::createFromTimestamp($value)->format('Y-m-d H:i:s');
    }
    return NULL;
//    return DateTimePlus::createFromTimestamp(time())->format('Y-m-d H:i:s');
  }
  
  function autoGeneratedVal($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property){
    return $this->idval+1;
  }
  
  function getNodeModifiedValue($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property){
    $source = $row->getSource();
    $data = \Drupal\Core\Database\Database::getConnection('default', $source['target'])
      ->select('node', 'source_table_name')
      ->fields('source_table_name',['changed'])
      ->condition('source_table_name.nid', $value)
      ->execute()
      ->fetchField();
//    print_r($data);exit;
    return $data;
  }
}