<?php

/**
 * @file
 * Contains custom_migration.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_migration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_migration module.
    case 'help.page.custom_migration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Migration Scripts and Plugins') . '</p>';
      return $output;
    
    default:
  }
}


function custom_migration_schema() {
  $schema = [];
  
  return $schema;
  
}